[package]
name = "flight_tracking_erau_se300"
version = "0.1.0"
edition = "2018"
description = "An app that displays the path of planes through the country of United States"
license = "MIT"

[dependencies]
conrod_core = "0.75.0"
conrod_winit = "0.75.0"
conrod_glium = "0.75.0"
glium = "0.28"
winit = "0.23"
find_folder =  "0.3.0"
