[package]
name = "flight_tracking"
version = "0.1.0"
edition = "2018"

[dependencies]
conrod_core = "0.75.0"
conrod_winit = "0.75.0"
conrod_glium = "0.75.0"
glium = "0.28"
winit = "0.23"
find_folder =  "0.3.0"
image = "0.22"
rand = "0.8.4"
